### PR TITLE
Fixes and Stuff

### LINKED ISSUE #61: [Roots 3] lit pyre does not provide light
When lit the pyre does not affect light levels.

### PR DESCRIPTION
**Pull request by Davoleo**
Content:

- [x] Pyre Lights up the area around during crafting recipes and rituals |  Fix #61 
- [ ] Flower Growth Ritual 
- [x] Armor Model textures
- [x] Wildwood armor patchouli book entry
- [x] Sylvan armor patchouli book entry
- [x] Wildwood armor advancement
- [x] Sylvan armor advancement

### CODE REVIEW

File: src/main/java/epicsquid/roots/entity/ritual/EntityRitualFlowerGrowth.java [hunk 1]
```diff
@@ -20,21 +27,42 @@ public EntityRitualFlowerGrowth(World worldIn)
     public void onUpdate()
     {
         ticksExisted++;
```
Comment (duely) [inline src/main/java/epicsquid/roots/entity/ritual/EntityRitualFlowerGrowth.java]: At least from what I understand of entities, the `ticksExisted` field is automatically updated by `World::updateEntities`. I noticed that you changed your 100 to a 200, implying it was happening too quickly? Probably because it was double-ticking. 

From `World.java:1862` (at least in my decompiled version)

```java
            try
            {
                if(entity.updateBlocked) continue;
                ++entity.ticksExisted;
                entity.onUpdate();
            }
```

Comment (Davoleo) [reply src/main/java/epicsquid/roots/entity/ritual/EntityRitualFlowerGrowth.java]: Well, I saw it was used in others ritual entities as well so I added it as well...
but I had no idea that `ticksExisted` gets automatically updated
https://github.com/EpicSquid/Roots/blob/master/src/main/java/epicsquid/roots/entity/ritual/EntityRitualLife.java#L26

File: src/main/java/epicsquid/roots/entity/ritual/EntityRitualBase.java [hunk 2]
```diff
@@ -25,6 +28,13 @@ public void setPosition(double x, double y, double z) {
     this.z = z;
   }
 
+  @Nonnull
+  @Override
+  public BlockPos getPosition()
```
Comment (Davoleo) [inline src/main/java/epicsquid/roots/entity/ritual/EntityRitualBase.java]: I added this because I needed to get the center position of the ritual, but I don't know if there's a better way to do it 🤔

**Comment by Davoleo** [comment]
so, is everything so far fine?
now the only issue I have is that the ritual doesn't start, I mean, I can't even see the flame effect

**Comment by Davoleo** [comment]
feel free to ask me changes on the descriptions too, if you think there could be a more appropriate way of writing them

File: src/main/java/epicsquid/roots/entity/ritual/EntityRitualFlowerGrowth.java (hunk 1 above)
Comment (EpicSquid) [reply src/main/java/epicsquid/roots/entity/ritual/EntityRitualFlowerGrowth.java]: It has that in every ritual. Worth testing without to see if it is working now

**Comment by EpicSquid** [comment]
As for the ritual not starting, I will take a proper look at that soon.

File: src/main/java/epicsquid/roots/entity/ritual/EntityRitualFlowerGrowth.java (hunk 1 above)
Comment (duely) [reply src/main/java/epicsquid/roots/entity/ritual/EntityRitualFlowerGrowth.java]: From what I can tell entity.ticksExisted is ticked before onUpdate is called unless it's blocked, at least by `updateEntityWithOptionalForce`:
